project_id = "qasomfndnjuixgjmjwcm"

[functions.create-admin-user]
verify_jwt = false

[functions.change-user-password]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-user-access-code]
verify_jwt = false

[functions.notify-service-order-email]
verify_jwt = false

[functions.notify-accident-email]
verify_jwt = false

[functions.send-supplier-order-email]
verify_jwt = false

[functions.paypal-charge]
verify_jwt = false

[functions.backup-data]
verify_jwt = false

[functions.auth-login-challenge]
verify_jwt = false

[functions.auth-send-otp]
verify_jwt = false

[functions.auth-verify-otp]
verify_jwt = false

[functions.auth-complete-password-reset]
verify_jwt = false
