-- Staging ONLY: usfeoerkpcafxxlyuldl. Do not apply to Production.
-- Migration: OpenProspector central persistent storage for B2B fleet & safety officer leads.
-- Zero impact on active customer databases, CRM, or Telemarketing.

CREATE TABLE IF NOT EXISTS public.prospect_leads (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_number integer GENERATED BY DEFAULT AS IDENTITY,
  company_name text NOT NULL,
  company_hp text,
  industry text DEFAULT '',
  city text DEFAULT '',
  region text DEFAULT '',
  address text DEFAULT '',
  website text DEFAULT '',
  phone text DEFAULT '',
  email text DEFAULT '',
  company_size text DEFAULT '',
  fleet_info jsonb DEFAULT '{}'::jsonb,
  fleet_type text DEFAULT '',
  score integer DEFAULT 90,
  status text NOT NULL DEFAULT 'new'
    CHECK (status IN ('new', 'review', 'contacted', 'meeting', 'quote', 'won', 'lost', 'rejected')),
  found_date text DEFAULT '',
  updated_date text DEFAULT '',
  is_safety_officer_lead boolean DEFAULT false,
  certified_professional jsonb,
  safety_officer jsonb,
  lead_reason text DEFAULT '',
  facts jsonb DEFAULT '{}'::jsonb,
  evidence jsonb DEFAULT '[]'::jsonb,
  people jsonb DEFAULT '[]'::jsonb,
  multi_phones jsonb DEFAULT '[]'::jsonb,
  multi_mails jsonb DEFAULT '[]'::jsonb,
  notes text DEFAULT '',
  raw_payload jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_prospect_leads_company_hp UNIQUE (company_hp)
);

-- Unique index on company_hp to guarantee zero duplicates while allowing nulls
CREATE UNIQUE INDEX IF NOT EXISTS idx_prospect_leads_hp_unique
  ON public.prospect_leads (company_hp)
  WHERE company_hp IS NOT NULL AND btrim(company_hp) <> '';

-- Search and filter indexes
CREATE INDEX IF NOT EXISTS idx_prospect_leads_name ON public.prospect_leads (lower(trim(company_name)));
CREATE INDEX IF NOT EXISTS idx_prospect_leads_status ON public.prospect_leads (status);
CREATE INDEX IF NOT EXISTS idx_prospect_leads_safety ON public.prospect_leads (is_safety_officer_lead);
CREATE INDEX IF NOT EXISTS idx_prospect_leads_created ON public.prospect_leads (created_at DESC);

-- Enable RLS
ALTER TABLE public.prospect_leads ENABLE ROW LEVEL SECURITY;

-- Staging Policies: Allow anon and authenticated to SELECT, INSERT, UPDATE in Staging
DROP POLICY IF EXISTS "prospect_leads_select_policy" ON public.prospect_leads;
CREATE POLICY "prospect_leads_select_policy" ON public.prospect_leads
  FOR SELECT TO anon, authenticated
  USING (true);

DROP POLICY IF EXISTS "prospect_leads_insert_policy" ON public.prospect_leads;
CREATE POLICY "prospect_leads_insert_policy" ON public.prospect_leads
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

DROP POLICY IF EXISTS "prospect_leads_update_policy" ON public.prospect_leads;
CREATE POLICY "prospect_leads_update_policy" ON public.prospect_leads
  FOR UPDATE TO anon, authenticated
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "prospect_leads_delete_policy" ON public.prospect_leads;
CREATE POLICY "prospect_leads_delete_policy" ON public.prospect_leads
  FOR DELETE TO authenticated
  USING (true);
