-- Staging ONLY: usfeoerkpcafxxlyuldl. Do not apply to Production.
-- OpenProspector: enrichment queue (batches / items) and append-only audit log.
-- Additive only: new tables, no change to public.prospect_leads.
-- Lead data is written only after a human approves a finding (client: OpenProspector "העשרת לידים").
-- Access: super_admin only (public.has_role). No API keys are stored here.

CREATE TABLE IF NOT EXISTS public.prospect_enrichment_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'running', 'paused', 'done', 'cancelled')),
  dry_run boolean NOT NULL DEFAULT true,
  grounding boolean NOT NULL DEFAULT true,
  max_leads integer NOT NULL DEFAULT 20 CHECK (max_leads BETWEEN 1 AND 20),
  model text,
  request_count integer NOT NULL DEFAULT 0,
  tokens_used integer NOT NULL DEFAULT 0,
  estimated_cost numeric(12, 4),
  enrichment_started_at timestamptz,
  enrichment_finished_at timestamptz,
  created_by uuid DEFAULT auth.uid(),
  created_by_email text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.prospect_enrichment_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_id uuid NOT NULL REFERENCES public.prospect_enrichment_batches(id) ON DELETE CASCADE,
  lead_id uuid NOT NULL REFERENCES public.prospect_leads(id) ON DELETE CASCADE,
  company_hp text,
  status text NOT NULL DEFAULT 'queued'
    CHECK (status IN ('queued', 'running', 'done', 'failed', 'manual_review')),
  decision text CHECK (decision IN ('approved', 'rejected', 'partial')),
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 2),
  request_count integer NOT NULL DEFAULT 0,
  request_payload jsonb,
  findings jsonb,
  validation jsonb,
  grounding jsonb,
  applied jsonb,
  error text,
  model text,
  tokens_used integer,
  started_at timestamptz,
  finished_at timestamptz,
  decided_by uuid,
  decided_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT uq_prospect_enrichment_item UNIQUE (batch_id, lead_id)
);

CREATE INDEX IF NOT EXISTS idx_prospect_enrichment_items_batch ON public.prospect_enrichment_items (batch_id, status);
CREATE INDEX IF NOT EXISTS idx_prospect_enrichment_items_lead ON public.prospect_enrichment_items (lead_id);

CREATE TABLE IF NOT EXISTS public.prospect_enrichment_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at timestamptz NOT NULL DEFAULT now(),
  actor uuid DEFAULT auth.uid(),
  actor_email text,
  action text NOT NULL,
  batch_id uuid,
  item_id uuid,
  lead_id uuid,
  model text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS idx_prospect_enrichment_audit_batch ON public.prospect_enrichment_audit (batch_id, at DESC);

-- A batch can never hold more leads than its max_leads (<= 20)
CREATE OR REPLACE FUNCTION public.prospect_enrichment_items_cap()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
DECLARE cap integer; n integer;
BEGIN
  SELECT max_leads INTO cap FROM public.prospect_enrichment_batches WHERE id = NEW.batch_id;
  SELECT count(*) INTO n FROM public.prospect_enrichment_items WHERE batch_id = NEW.batch_id;
  IF n >= coalesce(cap, 20) THEN
    RAISE EXCEPTION 'batch % already has % leads (max %)', NEW.batch_id, n, coalesce(cap, 20);
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS trg_prospect_enrichment_items_cap ON public.prospect_enrichment_items;
CREATE TRIGGER trg_prospect_enrichment_items_cap BEFORE INSERT ON public.prospect_enrichment_items
  FOR EACH ROW EXECUTE FUNCTION public.prospect_enrichment_items_cap();

-- RLS: super_admin only
ALTER TABLE public.prospect_enrichment_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prospect_enrichment_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.prospect_enrichment_audit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pe_batches_select ON public.prospect_enrichment_batches;
CREATE POLICY pe_batches_select ON public.prospect_enrichment_batches FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role));
DROP POLICY IF EXISTS pe_batches_insert ON public.prospect_enrichment_batches;
CREATE POLICY pe_batches_insert ON public.prospect_enrichment_batches FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'::app_role));
DROP POLICY IF EXISTS pe_batches_update ON public.prospect_enrichment_batches;
CREATE POLICY pe_batches_update ON public.prospect_enrichment_batches FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'::app_role));

DROP POLICY IF EXISTS pe_items_select ON public.prospect_enrichment_items;
CREATE POLICY pe_items_select ON public.prospect_enrichment_items FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role));
DROP POLICY IF EXISTS pe_items_insert ON public.prospect_enrichment_items;
CREATE POLICY pe_items_insert ON public.prospect_enrichment_items FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'::app_role));
DROP POLICY IF EXISTS pe_items_update ON public.prospect_enrichment_items;
CREATE POLICY pe_items_update ON public.prospect_enrichment_items FOR UPDATE TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role))
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'::app_role));
-- removing a lead from the batch is allowed only before it was processed
DROP POLICY IF EXISTS pe_items_delete ON public.prospect_enrichment_items;
CREATE POLICY pe_items_delete ON public.prospect_enrichment_items FOR DELETE TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role) AND status = 'queued' AND attempts = 0);

-- audit is append-only: no UPDATE / DELETE policies
DROP POLICY IF EXISTS pe_audit_select ON public.prospect_enrichment_audit;
CREATE POLICY pe_audit_select ON public.prospect_enrichment_audit FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::app_role));
DROP POLICY IF EXISTS pe_audit_insert ON public.prospect_enrichment_audit;
CREATE POLICY pe_audit_insert ON public.prospect_enrichment_audit FOR INSERT TO authenticated
  WITH CHECK (public.has_role(auth.uid(), 'super_admin'::app_role) AND actor = auth.uid());
